### PR TITLE
i6 = 1 instead if i6 = 2

### PR DESCRIPTION
**Pull request by Daeels**
Hi hyper, thanks for the solution. For the value of i6, I think that it should be 1 (index offset) like i2.

### CODE REVIEW

**Comment by hyperneutrino** [comment]
No, this makes it give the wrong answer. Remember that `[[6]]` is larger than `[[2]]`, so the index of `[[6]]` starts one higher because of that.

**Comment by Daeels** [comment]
image

**Comment by hyperneutrino** [comment]
Oh. That's because of the `+ [[[2]], [[6]]]`. You're not supposed to have that there; if you include that then you should start `i2` and `i6` at `1` but you're not supposed to have that. I accidentally left it in since I was demonstrating something during the video but I removed that a long time ago.

**Comment by Daeels** [comment]
> Oh. That's because of the `+ [[[2]], [[6]]]`. You're not supposed to have that there; if you include that then you should start `i2` and `i6` at `1` but you're not supposed to have that. I accidentally left it in since I was demonstrating something during the video but I removed that a long time ago.

Oh Yeah, I didn't pay attention. there is no `+ [[[2]], [[6]]]` in your Code. My bad.
Thanks a lot :)

**Pull request closed without merging**
